[package]
name = "leo-pgjson"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Exporta tablas PostgreSQL de una conexión a JSON"

[dependencies]
clap = { workspace = true, features = ["env"] }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
