[package]
name = "leo-vad"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Detector de voz/silencio a bajo nivel (WebRTC VAD)"

[dependencies]
thiserror.workspace = true
webrtc-vad.workspace = true
leo-audio.workspace = true

[dev-dependencies]
leo-audio.workspace = true
